### ISSUE TITLE
the server is closing, because the router dowload-media is broken the server

### ISSUE THREAD

**Issue by aspiretony** [ndalu-id/baileys-api#16]
/api/whatsapp/download-media broken server the error:

`Error: item-not-found
at assertNodeErrorFree (/www/wwwroot/zapi.wasdesk.com.br/src/baileys/lib/WABinary/generic-utils.js:56:15)
at query (/www/wwwroot/zapi.wasdesk.com.br/src/baileys/lib/Socket/socket.js:128:48)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.profilePictureUrl (/www/wwwroot/zapi.wasdesk.com.br/src/baileys/lib/Socket/chats.js:370:24)
at async getPpUrl (/www/wwwroot/zapi.wasdesk.com.br/src/router/model/whatsapp.js:632:15)
at async /www/wwwroot/zapi.wasdesk.com.br/src/router/model/whatsapp.js:181:25 {
data: 404,
isBoom: true,
isServer: true,
output: {
statusCode: 500,
payload: {
statusCode: 500,
error: 'Internal Server Error',
message: 'An internal server error occurred'
},
headers: {}
}
}`

tested with json "token .... message.... and without json, and 
random json

all request broken server.

How could I send everything via base64? (imageMessage, audio....)

**Comment by ngadimin51** [comment]
Will check after new year.
Base64 will increase the size. If still qant to use U can edit here

src/router/model/whatsapp.js
Line 796

**Comment by aspiretony** [comment]
Thanks well I'm bad at typescript and derivatives but I try to help as much as possible

**Comment by aspiretony** [comment]
Thank you very much, I enabled audio, video, additive, document following the pattern of your project, if you want I can pull it from github.
