### ISSUE TITLE
Error after disconnect

### ISSUE THREAD

**Issue by Smallkan** [ndalu-id/baileys-api#19]
`"level":40,"time":"2023-01-18T17:03:02.647Z","pid":21576,"hostname":"DESKTOP-UN76EN2","stack":"Error: mutex start\n    at C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:15:31\n    at Object.mutex (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\make-mutex.js:35:15)\n    at handleNotification (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:422:29)\n    at execTask (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:554:20)\n    at processNodeWithBuffer (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:551:15)\n    at WebSocket.<anonymous> (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\messages-recv.js:569:9)\n    at WebSocket.emit (events.js:400:28)\n    at C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:222:35\n    at Object.decodeFrame (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Utils\\noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (C:\\User\\whatsapp\\chat\\whatsapp-backend-cpm\\node_modules\\@adiwajshing\\baileys\\lib\\Socket\\socket.js:198:15)","waitOver":true,"msg":"possible mutex deadlock"}`

`node:21576) UnhandledPromiseRejectionWarning: Error: Timed Out
    at C:\User\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Utils\generics.js:157:32
(node:21576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 19)
Error: Connection Closed
    at sendRawMessage (C:\User\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:50:19) 
    at sendNode (C:\User\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:61:16)       
    at query (C:\User\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:125:15)
    at Object.profilePictureUrl (C:\User\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:370:30)
    at getPpUrl (C:\User\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:763:33)
    at connectToWhatsApp (C:\User\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:43:27)
    at Timeout._onTimeout (C:\User\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:76:27)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  data: null,
  isBoom: true,
  isServer: false,
nction without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 22)
Error: Connection Closed
    at sendRawMessage (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:50:19) 
    at sendNode (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:61:16)       
    at query (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\socket.js:125:15)
    at Object.profilePictureUrl (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\node_modules\@adiwajshing\baileys\lib\Socket\chats.js:370:30)
    at getPpUrl (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:763:33)
    at connectToWhatsApp (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:43:27)
    at Timeout._onTimeout (C:\Smallkan\whatsapp\chat\whatsapp-backend-cpm\src\router\model\whatsapp.js:76:27)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  data: null,
  isBoom: true,  isServer: false,  output: {    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },    headers: {}
  }
}
> Interval check connection TOKEN: d61fce87-1736-4154-b7c4-761996dab1d4 { status: true, message: 'Already connected' }`

Whenever I disconnect through whatsapp, it generates a closed connection loop.

I am using win-dev command
Can you help?

**Comment by zymaxaservices** [comment]
Try Latest Version or Disconnect after fully connected and Synced
